"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../src/componants/layouts/Navbar";
import Footer from "../src/componants/layouts/Footer";
// import { Provider } from "react-redux";
// import { store } from "@/redux/store";
import { Metadata } from "@/types/metadata";
import { useApollo } from "@/libs/useApollo";
import { ApolloProvider } from "@apollo/client";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  const apolloClient = useApollo();
  return (
    <ApolloProvider client={apolloClient}>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {/* <Provider store={store}> */}
          {children}
          {/* </Provider> */}
          <Footer />
        </body>
      </html>
    </ApolloProvider>
  );
}
